services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ivan-balbino-portfolio:latest
    container_name: portfolio-web
    ports:
      - "3000:3000"
    restart: unless-stopped
